package com.techknightsrtu.crosstalks.app.helper.constants;

import com.techknightsrtu.crosstalks.R;

import java.util.ArrayList;

public class Avatar {

    public static  ArrayList<Integer> avatarList = new ArrayList<Integer>() {
        {
            add(R.drawable.ic_amethyst);
            add(R.drawable.ic_aquaman);
            add(R.drawable.ic_avatar);
            add(R.drawable.ic_batman);
            add(R.drawable.ic_beast);
            add(R.drawable.ic_black_blood);
            add(R.drawable.ic_boruto);
            add(R.drawable.ic_brutus);
            add(R.drawable.ic_captain_america);
            add(R.drawable.ic_chewbacca);
            add(R.drawable.ic_cookie_monster);
            add(R.drawable.ic_cyborg);
            add(R.drawable.ic_cyclops_marvel);
            add(R.drawable.ic_darth_vader);
            add(R.drawable.ic_deadpool);
            add(R.drawable.ic_deathstroke);
            add(R.drawable.ic_finn);
            add(R.drawable.ic_frankensteins);
            add(R.drawable.ic_gambit);
            add(R.drawable.ic_green_lantern);
            add(R.drawable.ic_groot);
            add(R.drawable.ic_hammerstein);
            add(R.drawable.ic_harley_quinn);
            add(R.drawable.ic_hawkeye);
            add(R.drawable.ic_hawkgirl);
            add(R.drawable.ic_hellcat);
            add(R.drawable.ic_hulk);
            add(R.drawable.ic_human_torch);
            add(R.drawable.ic_ice_king);
            add(R.drawable.ic_iron_man);
            add(R.drawable.ic_itachi_uchiha);
            add(R.drawable.ic_jake);
            add(R.drawable.ic_jean_grey);
            add(R.drawable.ic_jessica_jones);
            add(R.drawable.ic_jetpack_joyride);
            add(R.drawable.ic_joe_pineapples);
            add(R.drawable.ic_joker);
            add(R.drawable.ic_kakashi_hatake);
            add(R.drawable.ic_kermit);
            add(R.drawable.ic_logan);
            add(R.drawable.ic_luke_cage);
            add(R.drawable.ic_magneto);
            add(R.drawable.ic_mongrol);
            add(R.drawable.ic_mummy);
            add(R.drawable.ic_mystique);
            add(R.drawable.ic_naruto);
            add(R.drawable.ic_nightwing);
            add(R.drawable.ic_ninja_turtle);
            add(R.drawable.ic_pennywise);
            add(R.drawable.ic_popeye);
            add(R.drawable.ic_professor_x);
            add(R.drawable.ic_purple_man);
            add(R.drawable.ic_rogue);
            add(R.drawable.ic_smurf);
            add(R.drawable.ic_sonic);
            add(R.drawable.ic_spiderman);
            add(R.drawable.ic_storm_marvel);
            add(R.drawable.ic_stormtrooper);
            add(R.drawable.ic_suicide_joker);
            add(R.drawable.ic_super_mario);
            add(R.drawable.ic_superman);
            add(R.drawable.ic_thanos);
            add(R.drawable.ic_the_flash);
            add(R.drawable.ic_the_professor);
            add(R.drawable.ic_thor);
            add(R.drawable.ic_undyne);
            add(R.drawable.ic_venom);
            add(R.drawable.ic_wolverine);
            add(R.drawable.ic_wonder_woman);
            add(R.drawable.ic_yoda);
        }
    };

    public static ArrayList<String> nameList = new ArrayList<String>(){
        {
            add("Amethyst");
            add("Aquaman");
            add("Avatar");
            add("Batman");
            add("Beast");
            add("Black Blood");
            add("Boruto");
            add("Brutus");
            add("Captain America");
            add("Chewbacca");
            add("Cookie Monster");
            add("Cyborg");
            add("Cyclops Marvel");
            add("Darth Vader");
            add("Deadpool");
            add("Deathstroke");
            add("Finn");
            add("Frankenstein");
            add("Gambit");
            add("Green Lantern");
            add("Im Groot");
            add("Hammerstein");
            add("Harley Quinn");
            add("Hawkeye");
            add("Hawk Girl");
            add("Hellcat");
            add("Hulk");
            add("Human Torch");
            add("Ice King");
            add("Iron Man");
            add("Itachi Uchiha");
            add("Jake");
            add("Jean Grey");
            add("Jessica Jones");
            add("Jetpack Joyride");
            add("Joe Pineapples");
            add("Joker");
            add("Kakashi Hatake");
            add("Kermit");
            add("Logan");
            add("Luke Cage");
            add("Magneto");
            add("Mongrol");
            add("Mummy");
            add("Mystique");
            add("Naruto");
            add("Night Wing");
            add("Ninja Turtle");
            add("Pennywise");
            add("Popeye");
            add("Professor X");
            add("Purple Man");
            add("Rogue");
            add("Smurf");
            add("Sonic");
            add("Spider Man");
            add("Storm Marvel");
            add("Stormtrooper");
            add("Suicide Joker");
            add("Mario");
            add("Superman");
            add("Thanos");
            add("The Flash");
            add("The Professor");
            add("Thor");
            add("Undyne");
            add("Venom");
            add("Wolverine");
            add("Wonder Women");
            add("Yoda");
        }
    };
}
